<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>38ea9f30-5c1b-4822-ac98-e6af1f388a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-lg.btn-block.fa-lg.shadow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a4233d9-9adb-461a-9537-3ffb60dbcfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-lg btn-block fa-lg shadow</value>
      <webElementGuid>4bc1f707-9b37-4fa7-8f62-4af0b6df241c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa2abc4d-a6a0-42e1-8bf4-aeaaf345b716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                          LOGIN
                        </value>
      <webElementGuid>5003a7fc-6cc7-43f9-8062-2dff77b88994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-body&quot;]/section[@class=&quot;gradient-form&quot;]/div[@class=&quot;container py-5&quot;]/div[@class=&quot;row d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;col-xl-10&quot;]/div[@class=&quot;card login-card text-black shadow&quot;]/div[@class=&quot;row g-0&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;card-body p-md-5 mx-md-4&quot;]/form[1]/div[@class=&quot;text-center pt-1 mt-2 pb-1&quot;]/button[@class=&quot;btn btn-secondary btn-lg btn-block fa-lg shadow&quot;]</value>
      <webElementGuid>cef9726a-e326-4dec-85be-9787234c7442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2b3ef146-8d8a-43d5-b8f3-64310eacb458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>712713d8-83c9-4196-a4bf-3156f65ff536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolong isi password'])[1]/following::button[1]</value>
      <webElementGuid>01f1ac34-52de-4949-8386-15ccf799d457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>5430769e-24dd-4aa6-b0d2-547e55594604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>63747e6d-52f8-4c87-bc2d-19866a7076b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                          LOGIN
                        ' or . = '
                          LOGIN
                        ')]</value>
      <webElementGuid>ac6288fa-bd89-4323-81f6-ab5ccfc1231b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
